a = input('digite algo: ')
print ('O tipo primitivo é:', type(a))
print('Só tem espaços?', a.isspace())
print('é um numeri?', a.isnumeric())
print('é alfabetico ? ', a.isalpha())
print('é alfanumerico?', a.isalnum())
print('Esta em maiúsculas ? ', a.isupper())
print('Esta em  minusculas ?', a.islower())
print('esta capitalizada', a.istitle())
